name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        php-versions: [8.2, 8.3, 8.4]

    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Switch PHP Version
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug

    - name: Validate composer.json and composer.lock files
      run: composer validate --no-interaction

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-versions }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress

    - name: Run test suite with coverage
      run: composer run-script test -- --stop-on-failure --coverage-clover clover.xml

    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_API }}
        # or
        # api-token: ${{ secrets.CODACY_API_TOKEN }}
        coverage-reports: clover.xml
        # or a comma-separated list for multiple reports
        # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>
